services:
  - type: web
    name: nowgoal-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT src.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
